language: python

python:
  - 3.7

install:
  - pip install -r requirements.txt

before_script:
  - python manage.py migrate
  - python manage.py collectstatic --noinput

script:
  - black --check .
  - python3.7 -m flake8 .
  - coverage run --source=mysite,polls manage.py test

after_script:
  - coveralls